### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by ghost**
`tablib`, `six` :versions updated.
`matplotlib`, `pandas` :added.

### CODE REVIEW

**Comment by libhide** [comment]
We don't really need matplotlib and pandas anymore. They were added for this feature we were trying to implement but it failed eventually. 

@deadbeatfour, @utk-dev decide on the requirements once on this thread and add a commit for them and **then** merge into level_up.

**Comment by ghost** [comment]
Then we should comment out the features that require matplotlib and pandas(because currently the website does not compile without them). If matplotlib is not required, then Six's version need not be updated as well @libhide

**Comment by theSage21** [comment]
That would be ideal. Actually you know what? The orfik module needs a rewrite. Right @libhide ?

**Comment by abhishekchak52** [comment]
We should ideally also move to pipenv right?

**Comment by theSage21** [comment]
yes. I haven't had a chance to try it though since my dev environment is custom rolled.

**Comment by abhishekchak52** [comment]
Nice. Tell me about it?

**Comment by theSage21** [comment]
Nothing fancy. All venvs are in the top level folder of respective projects. One global env lives in my home folder. A shortcut to activate current folder's venv + pip + make lets me get reproducible projects. 

I'm reading up on docker for more stability.

Works pretty well since I'm not really deploying to production and only experimenting. The day I find a need to switch I'm going to switch pretty fast to pipenv though.

**Comment by libhide** [comment]
@theSage21 Orfik works and is stable but of course a re-write is always fun. What are the plans for Orfik this summer, @deadbeatfour?

Also, @utk-dev, just go through the project and remove all the matplotlib stuff and get it to compile?

**Pull request closed without merging**
