### PR TITLE
Lb up

### PR DESCRIPTION
**Pull request by theSage21**
- I gave up on D3. Too much going on right now to learn another thing. I'll stick to what I know for now.
- Charts are generated for the Orfik leaderboard and uploaded as base64 encoded strings. 
- X axis denotes time and spans the duration of the contest.
- Y axis denotes levels and spans 0 to `max_level` (This is automatically detected from the max question number available).
- User levels are jittered to add an organic feel to the whole thing (+ you cannot see anyone if they are all on the same spot).
- Only correct attempts are counted to reduce plotting load.
- Legend lists people in ranking order. (This has not been tested for tied levels. The way I've set it up it should work)
- Title is the name given to the event.

### CODE REVIEW

**Comment by theSage21** [comment]
@libhide @deadbeatfour squash and merge if you can. I still make a mess of branches and commits.

**Review by libhide — CHANGES_REQUESTED** [review]
Could you pip freeze into the requirements file please? 😅

**Comment by libhide** [comment]
Also, a side note on things as they stand right now: I'm guessing you're using scipy for the leaderboard stuff, right? There's an issue we're facing – due to the limited storage we have on pythonanywhere, scipy has issues installing. 🙃

**Comment by theSage21** [comment]
All of this stuff comes installed in the global environment

**Comment by libhide** [comment]
@theSage21 I did a simple test. I setup a fresh orfik instance with two users and solved one question from each account. The leaderboard page gives me the following.

screen shot 2017-02-08 at 5 16 00 pm

**Comment by theSage21** [comment]
Ah I know what this is. I'll fix this as soon as I get home.

**Comment by theSage21** [comment]
@libhide I've pushed a fix. See if that works at your place.

**Review by libhide — APPROVED** [review]

**Comment by libhide** [comment]
Stuff's working for me. @deadbeatfour, can you take it for a spin asap? I'm still a little worried about the scipy dependency and if pythonanywhere will be able to handle it @theSage21.

**Comment by abhishekchak52** [comment]
Should we merge this or delete this branch? @compsoc-ssc/alumni

**Comment by theSage21** [comment]
Let's drop it since it's not that good anyways. You should be able to let one of the juniors figure out how to do this without the backend plotting setup.

**Comment by abhishekchak52** [comment]
Alright then.

**Pull request closed without merging**
