### PR TITLE
Cybercept 2017 Upgrade 🎉 

### PR DESCRIPTION
**Pull request by libhide**
This pull request contains the updates for Cybercept 2017. Here's a quick summary. 

1. Events now work completely through the admin. No need to use start and end variables.
2. A new event **Sell-it!** has its own app!
3. Orfik has a shiny new pre-registration user flow.
4. Better ordering for the CompSoc members section.
5. Misc. bug fixes.

I hope I didn't miss anything. @deadbeatfour please pull the branch and test it thoroughly. Let's have a great Cybercept!

### CODE REVIEW

**Comment by abhishekchak52** [comment]
@libhide There are a few issues.
1. There's no link for the leaderboard
Screenshot
2. Player still able to access first unsolved question after orfik has ended.

**Comment by theSage21** [comment]
Damn. We need a test suite for this beast.

**Comment by theSage21** [comment]
@deadbeatfour I need client secrets to debug locally

**Comment by theSage21** [comment]
I looked at the code. After the event the questions are still visible, however they can no longer submit answers to those questions. Seems fair no?

**Comment by abhishekchak52** [comment]
@theSage21 It's perfectly cool. I'm just suggesting we redirect them to the homepage if they try to access a question after orfik has ended. it's not urgent.

**Comment by libhide** [comment]
Okay so for some reason @theSage21's mathplotlib stuff isn't in this branch. I have no idea how this happened. Can one of you look into this? I'm afk right now.

**Comment by theSage21** [comment]
I removed that part. Fix events. Another branch will have lb update. I'm
trying to get into good habits

**Comment by libhide** [comment]
@theSage21 Okay cool!

**Pull request merged**
